MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
    RPN:
      PRE_NMS_TOPK_TEST: 6000
      POST_NMS_TOPK_TEST: 1000
    ROI_HEADS:
      NAME: "Res5ROIHeads"
  WEIGHTS: "/root/data/zq/unsup_det/marvel_pretrain/selfsup_weights.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
DATASETS:
  TRAIN: ("smd_train", "smd_val")
  TEST: ("smd_test",)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.02
  STEPS: (60000, 80000)
  MAX_ITER: 90000
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
VERSION: 2